### ISSUE TITLE
I can't find the flatpak

### ISSUE THREAD

**Issue by ghost** [fastrizwaan/Rosalie-s-Mupen-GUI_flatpak#1]
If I search for your flatpak in pamac,then I can't find it
![image](https://user-images.githubusercontent.com/68649672/108152197-cf69db00-70d8-11eb-80c0-431ad022f418.png)

**Comment by fastrizwaan** [comment]
```
wget https://github.com/fastrizwaan/Rosalie-s-Mupen-GUI_flatpak/raw/main/%5Bflatpak-linux64%5DRosalies_.Mupen_.G.U.I/Rosalies_Mupen_GUI.flatpak

flatpak install --user Rosalies_Mupen_GUI.flatpak

flatpak run org.flatpakwine64.Rosalies_Mupen_GUI

```

**Comment by fastrizwaan** [comment]
It's not distributed by Flathub or other means, you have to manuall installed as commands given above.
